server:
  port: ${PORT:9094}
  servlet:
    context-path: ${CONTEXT_PATH:/}

app:
  frontend:
    url: ${APP_URL:http://localhost:3001}

#spring:
#  datasource:
#    url: ${DB_URL:jdbc}
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    driver-class-name: org.postgresql.Driver

spring:
  datasource:
    url: ${DB_URL:}
    username: ${DB_USERNAME:}
    password: ${DB_PASSWORD:}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:none}
    show-sql: false
    properties:
      hibernate:
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true

azure:
  storage:
    connection-string: ${AZURE_STORAGE_CONNECTION_STRING}
    container-name: ${AZURE_STORAGE_CONTAINER_NAME}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}
    client-secret: ${GOOGLE_CLIENT_SECRET}
  github:
    client-id: ${GITHUB_CLIENT_ID}
    client-secret: ${GITHUB_CLIENT_SECRET}

microservices:
  urls:
    api-gateway: ${API_GATEWAY_URL}
    user-service: ${USER_SERVICE_URL}
    core-service: ${CORE_SERVICE_URL}
    streaming-service: ${STREAMING_SERVICE_URL}
    messaging-service: ${MESSAGING_SERVICE_URL}

sendgrid:
  api-key: ${SENDGRID_API_KEY}
  from-email: ${SENDGRID_FROM_EMAIL:contact@zummitafrica.com}
  from-name: ${SENDGRID_FROM_NAME:datarango}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    hostname: localhost
    prefer-ip-address: false
    non-secure-port: 9094
    secure-port-enabled: false
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    info:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
  health:
    redis:
      enabled: false
    db:
      enabled: true

info:
  app:
    name: ${spring.application.name}
    description: DataRango Messaging Service
    version: 1.0.0
    encoding: UTF-8
    java:
      version: ${java.version}